### ISSUE TITLE
Missing package directoy

### ISSUE THREAD

**Issue by erichonkanen** [tildeio/simple-html-tokenizer#66]
Hey I just upgraded ember/cli/data from 3.0.0 to 3.4.1 and I'm seeing this in server output:
```
WARNING:
WARNING: /Users/eric/Projects/cannopy/build/client-web/node_modules/simple-html-tokenizer/commands:
WARNING:    Missing package directory
```
I do not have it as a dependency in my project but any idea what it's from?

**Comment by dcombslinkedin** [comment]
When you do 'ember build' or other ember commands, the first thing that happens is the code looks for any custom commands among the addons it finds. The addon-discovery process changed a while back (to a feature called 'package-info-cache'), which is generating these warnings as it finds issues with the package.json files of addons that are referenced.

**Comment by rwjblue** [comment]
We need to do a PR similar to https://github.com/kellyselden/ember-cli-funnel/pull/84 to move the in-repo addon into `devDependencies`.

@erichonkanen - Think you might have time to take a crack at it?

**Comment by erichonkanen** [comment]
@rwjblue isn't it already in there? `in-repo-commands`
```
  "devDependencies": {
    "@types/qunit": "^2.5.0",
    "broccoli-concat": "^3.0.5",
    "broccoli-funnel": "^2.0.1",
    "broccoli-merge-trees": "^3.0.0",
    "broccoli-rollup": "^2.0.0",
    "broccoli-tslinter": "^3.0.1",
    "broccoli-typescript-compiler": "^2.2.0",
    "ember-cli": "^3.0.0",
    "got": "^8.2.0",
    "in-repo-commands": "file:./commands",
    "nyc": "^11.4.1",
    "qunit": "^2.5.1",
    "rollup-plugin-sourcemaps": "^0.4.2",
    "symlink-self": "file:./lib/symlink-self",
    "tslint": "^5.9.1",
    "typescript": "^2.7.2"
  }
```

**Comment by rwjblue** [comment]
Oh, right, sorry. This was fixed by 
https://github.com/tildeio/simple-html-tokenizer/pull/61.

**Comment by erichonkanen** [comment]
gotcha, so likely some dependency uses this lib but is behind on version?

**Comment by rwjblue** [comment]
right, exactly

You can `npm ls simple-html-tokenizer` to see the heirarchy...

**Comment by ldalves** [comment]
Guys, I'm sorry if this seems redundant, but I'm new to all this and I'm seeing this message as well. Here's the output of the above command:
```
# npm ls simple-html-tokenizer
myapp@0.0.0 /myapp
+-- @fortawesome/ember-fontawesome@0.1.7
| `-- ember-ast-helpers@0.3.5
|   +-- @glimmer/compiler@0.27.0
|   | `-- simple-html-tokenizer@0.3.0
|   `-- @glimmer/syntax@0.27.0
|     `-- simple-html-tokenizer@0.3.0  deduped
`-- ember-cli-template-lint@1.0.0-beta.2
  `-- ember-template-lint@1.0.0-beta.5
    `-- @glimmer/compiler@0.36.2
      `-- @glimmer/syntax@0.36.2
        `-- simple-html-tokenizer@0.5.6
```
What's the exactly change I should do in order to fix it? :)

**Comment by erichonkanen** [comment]
@ldalves I resolved it by upgrading ember-cli-template-lint, looks like you also need to update fortawesome (if they've updated)

**Comment by ldalves** [comment]
@erichonkanen It seems I'm already using its latest version... I will check if there is anything else I could do. Thanks!
