### ISSUE TITLE
Line numbers are 1-indexed but columns are 0-indexed?

### ISSUE THREAD

**Issue by fivetanley** [tildeio/simple-html-tokenizer#87]
This is more of a general question, but it came up while trying to address https://github.com/glimmerjs/glimmer-vm/pull/953, which is a failing test around the location info for "valueless" attributes. While adding a test in this project's test suite, I noticed the following tests seem to indicate that *line numbers are 1-indexed* while *column numbers are 0-indexed*:

https://github.com/tildeio/simple-html-tokenizer/blob/5a7739761ffc4358dd46399b5a2b62da9e0d7ba6/tests/tokenizer-tests.ts#L318-L321

Is this accurate? If so, is there a historical example, spec, or other documentation I could read up on to understand why they use different indexes? I don't think I've seen any editor or website for code use 0-based indexes for column numbers before but I could be wrong.

If this isn't accurate, this could become a new issue to make columns one indexed (probably a breaking change?).

Thanks!

**Comment by rwjblue** [comment]
> line numbers are 1-indexed while column numbers are 0-indexed

Yes, this is correct.

> If so, is there a historical example, spec, or other documentation I could read up on to understand why they use different indexes?

This is what Handlebars uses, which I believe comes from jison (and likely bison). I am told that it is "commonplace" by @wycats when I mentioned it recently, but I don't personally have the context to site any specific original source.

**Comment by rwjblue** [comment]
Going to close as this isn't really a bug, but I totally agree with you that its unintuitive.

**Comment by rwjblue** [comment]
(oh also, if you use `ember-template-recast` as your parser it auto-corrects for this issue)
